#this file is added to practice AWS for Webclues job
version: 0.2

phases: 
  build:
    commands:
      - echo "Building docker image"
      - docker build -t docker.io/shivanij2304/python-webclues .
      - cat Shivani@23 | docker login --username shivanij2304 --password-stdin
      - docker push docker.io/shivanij2304/python-webclues
  post_build:
    commands:
    - echo "Build is successful."
