FROM ubuntu:latest as build

# Set the working directory in the image
WORKDIR /app

# Copy the files from the host file system to the image file system
COPY . /app

# Install the necessary packages
RUN apt-get update && apt-get install -y python3 python3-pip

# Set environment variables
ENV NAME World

# Run a command to start the application
CMD ["python3", "app.py"]

FROM python:3.12-slim-bookworm

COPY --from=build app/app.py .

ENV NAME World

CMD ["python3", "app.py"]
