name: My First GitHub Actions
on: [push]
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-070c810890c3a374f
          ec2-instance-type: t2.micro
          subnet-id: subnet-060d05aafbbe4d17d
          security-group-id: sg-0a4b7b1cfef8154b9
          #iam-role-name: my-role-name # optional, requires additional permissions
          #aws-resource-tags: > # optional, requires additional permissions
           # [
            #  {"Key": "Name", "Value": "ec2-github-runner"},
             # {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            #]
